server:
  port: 8090
spring:
  application:
    name: hello-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8717/eureka/
swagger:
  base-package: com.iflytek.helloservice.controller
  title: hello-service-api


